import { RibbitModulator } from "../modulator.js";
import { RibbitParamSources } from "../param.js";
import { RibbitEvent } from "../event.js";

// Web MIDI access is one permission prompt per page, so every MIDI object
// shares one request.
let midiAccess = null;
export function requestMidi() {
    if (!midiAccess) {
        if (typeof navigator === "undefined" || !navigator.requestMIDIAccess) {
            return Promise.reject(new Error("this browser has no Web MIDI (use Chrome or Edge)"));
        }
        midiAccess = navigator.requestMIDIAccess().catch((error) => {
            midiAccess = null;
            throw error;
        });
    }
    return midiAccess;
};

// The part every MIDI object shares: find the inputs matching a device
// query ("any", an id, or a fragment of the name), follow plugging and
// unplugging, filter by channel, and hand each message on as
// (kind, data1, data2). `status` says what it's listening to, or why not.
export class MidiListener {
    constructor(onMessage) {
        this.onMessage = onMessage;
        this.device = "any";
        this.channel = 0;
        this.status = "opening";
        this._inputs = [];
        this._disposed = false;
        this._handler = (message) => {
            const [statusByte, data1 = 0, data2 = 0] = message.data;
            if (this.channel && (statusByte & 0x0f) + 1 !== this.channel) return;
            this.onMessage(statusByte & 0xf0, data1, data2);
        };
    };

    async open(device = this.device) {
        this.device = String(device || "any");
        this._detach();
        try {
            const access = await requestMidi();
            if (this._disposed) return;
            access.addEventListener?.("statechange", this._onStateChange ??= () => this._attach(access));
            this._attach(access);
        } catch (error) {
            this.status = `unavailable: ${error.message}`;
        }
    };

    _attach(access) {
        this._detach();
        if (this._disposed) return;
        const wanted = this.device.toLowerCase();
        const inputs = [...access.inputs.values()].filter((input) => (
            wanted === "any" || input.id === this.device || (input.name ?? "").toLowerCase().includes(wanted)
        ));
        for (const input of inputs) input.addEventListener("midimessage", this._handler);
        this._inputs = inputs;
        const all = [...access.inputs.values()].map((input) => input.name).join(", ") || "none connected";
        this.status = inputs.length
            ? `listening: ${inputs.map((input) => input.name).join(", ")}`
            : `no MIDI input matching "${this.device}" (have: ${all})`;
    };

    _detach() {
        for (const input of this._inputs) input.removeEventListener("midimessage", this._handler);
        this._inputs = [];
    };

    // The device=/channel= options every MIDI object has.
    options() {
        return {
            device: { get: () => this.device, set: (value) => { this.open(value); } },
            channel: {
                get: () => this.channel,
                set: (value) => {
                    const n = Number(value);
                    if (!Number.isInteger(n) || n < 0 || n > 16) throw new Error(`invalid channel "${value}" — 0 (all) or 1-16`);
                    this.channel = n;
                },
            },
        };
    };

    dispose() {
        this._disposed = true;
        this._detach();
    };
};

export const SUSTAIN_CC = 64;

// A MIDI keyboard as a note generator. Patch it like any other generator —
// `/patch source=keys dest=lead.notes` — and every key played reaches that
// synth, with its velocity.
//
//     /add_modulator type=midiin name=keys device=arturia channel=0
//
// **Held notes.** A key sounds while it's held and is let go on key-up (a
// short `release` fade), with the sustain pedal (CC64) holding every note
// until it comes up — see RibbitSynth.triggerHeld for how a one-shot synth
// is made to stop early. `length` beats is the longest a note can ring if
// it's never let go (and all a worklet-voiced AE synth will ever play).
//
// **Signal.** Its output carries one controller, `cc` (the mod wheel, 1, by
// default), as 0..1 for param patches. For any other knob or fader, add a
// `midicc` per control.
//
// Notes are *pushed* the moment they arrive, not generated by the clock's
// lookahead (generateEvents is empty — it exists to mark this as a
// generator, which is what lets a `.notes` patch accept it). They sound only
// while the engine runs. It also *fires* (lastEventTime/lastVelocity) on
// every key, so anything with trigger= or strike= can follow the keyboard.
export class RibbitMidiIn extends RibbitModulator {
    constructor(audioContext, { name = "midiin", device = "any", channel = 0, cc = 1, length = 4, release = 0.15, transpose = 0, engine = null } = {}) {
        super(audioContext, { name });
        this.llm_summary = "A MIDI keyboard: every key played on device=<name fragment|any> (channel=0 for all, or 1-16) is a note on the tracks patched from it (/patch source=<this> dest=<track>.notes), held until key-up (release seconds fade), with the sustain pedal (CC64) holding notes; length beats caps a never-released note. Its signal output carries controller cc (default 1, the mod wheel) as 0..1 — add a midicc per extra knob.";
        this.engine = engine;
        // A generator that also publishes a signal (the cc) — hosts give it
        // a second outlet for that.
        this.signalOutput = true;
        this.cc = Number.isFinite(Number(cc)) ? Number(cc) : 1;
        this.lastNote = null;
        this.sustain = false;

        // pitch -> releases of the voices that key is holding; and the ones
        // the pedal is holding after their key came up.
        this._held = new Map();
        this._sustained = [];

        this._paramSources = new RibbitParamSources(audioContext);
        this.params = {
            length: this._paramSources.create(Number(length) || 4, { min: 0.03125, max: 64 }),
            release: this._paramSources.create(Number(release) || 0.15, { min: 0.005, max: 8 }),
            transpose: this._paramSources.create(Number(transpose) || 0, { min: -48, max: 48 }),
        };

        // The CC value, held and smoothed a little so a coarse 7-bit
        // controller doesn't zipper the param it's patched into.
        this.ccSource = audioContext.createConstantSource();
        this.ccSource.offset.value = 0;
        this.ccSource.connect(this.output);
        this.ccSource.start();

        this.midi = new MidiListener((kind, data1, data2) => this._receive(kind, data1, data2));
        this.midi.device = String(device || "any");
        this.midi.channel = Number(channel) || 0;
        this.options = {
            ...this.midi.options(),
            cc: {
                get: () => this.cc,
                set: (value) => {
                    const n = Number(value);
                    if (!Number.isInteger(n) || n < 0 || n > 127) throw new Error(`invalid cc "${value}" — 0-127`);
                    this.cc = n;
                },
            },
        };
        this.midi.open();
    };

    _receive(kind, data1, data2) {
        if (kind === 0x90 && data2 > 0) this.noteOn(data1, data2 / 127);
        else if (kind === 0x80 || kind === 0x90) this.noteOff(data1);
        else if (kind === 0xb0) {
            if (data1 === SUSTAIN_CC) this.setSustain(data2 >= 64);
            if (data1 === this.cc) this.ccSource.offset.setTargetAtTime(data2 / 127, this.audioContext.currentTime, 0.01);
            // 123: all notes off (and a panic on most controllers).
            if (data1 === 123) this.allNotesOff();
        }
    };

    // Public so a host (an on-screen keyboard) or a test can play without a
    // device.
    noteOn(pitch, velocity = 1) {
        const time = this.audioContext.currentTime;
        this.lastNote = pitch;
        this.lastVelocity = velocity;
        this.lastEventTime = time;
        if (this.audioContext.state !== "running") return;
        const secondsPerBeat = this.engine?.clock?.secondsPerBeat ?? 0.5;
        const event = new RibbitEvent({
            beat: 0,
            pitch: pitch + Math.round(this.params.transpose.getModulated()),
            velocity,
            duration: this.params.length.getModulated(),
        });
        const releases = this._held.get(pitch) ?? [];
        for (const destination of this.eventDestinations) {
            const synth = destination.source;
            if (!synth || synth.active === false) continue;
            const release = synth.triggerHeld(time, event, secondsPerBeat);
            if (!release) continue;
            synth.lastEventTime = time;
            releases.push(release);
        }
        this._held.set(pitch, releases);
    };

    noteOff(pitch) {
        const releases = this._held.get(pitch);
        if (!releases) return;
        this._held.delete(pitch);
        if (this.sustain) this._sustained.push(...releases);
        else this._release(releases);
    };

    setSustain(down) {
        this.sustain = down;
        if (down) return;
        this._release(this._sustained);
        this._sustained = [];
    };

    allNotesOff() {
        for (const releases of this._held.values()) this._release(releases);
        this._held.clear();
        this._release(this._sustained);
        this._sustained = [];
    };

    _release(releases) {
        const now = this.audioContext.currentTime;
        const fade = this.params.release.getModulated();
        for (const release of releases) release(now, fade);
    };

    // Nothing to schedule — see the class comment.
    generateEvents() {
        return [];
    };

    // Stopping the engine lets go of everything: a key held through /stop
    // would otherwise sound again, stuck, on /start.
    onClockStart() {
        this.allNotesOff();
    };

    describeState() {
        const held = this._held.size + (this._sustained.length ? ` (+${this._sustained.length} on the pedal)` : "");
        return `[${this.midi.status}${this.lastNote !== null ? `, last note ${this.lastNote}` : ""}, ${held} held${this.sustain ? ", sustain down" : ""}]`;
    };

    dispose() {
        this.allNotesOff();
        this.midi.dispose();
        this.ccSource.stop();
        this.ccSource.disconnect();
        this._paramSources.dispose();
    };
};
